refactor: update

diff --git a/.github/workflows/on-pull-request.yml b/.github/workflows/on-pull-request.yml
--- a/.github/workflows/on-pull-request.yml
+++ b/.github/workflows/on-pull-request.yml
@@ -54,18 +54,18 @@ jobs:
       - name: Run unit tests
         id: test
         run: |
-          # result=$(npm run test:workflow 2>&1)
-          # echo "result=$(npm run test:workflow 2>&1)"
-          # if [ $? -eq 0 ]; then
-          #   echo "tests-result=$result" >> $GITHUB_ENV
-          # else
-          #   echo "tests-result={"status":"failed"}" >> $GITHUB_ENV
-          #   exit 1
-          # fi
-
           result=$(npm run test:workflow --json)
-          # echo "tests-result=$($result | jq '.testResults[] | select(.status == "failed")')" >> $GITHUB_ENV
           echo "tests-result=$result" >> $GITHUB_ENV
+        # echo "tests-result=$($result | jq '.testResults[] | select(.status == "failed")')" >> $GITHUB_ENV
+          
+        # result=$(npm run test:workflow 2>&1)
+        # echo "result=$(npm run test:workflow 2>&1)"
+        # if [ $? -eq 0 ]; then
+        #   echo "tests-result=$result" >> $GITHUB_ENV
+        # else
+        #   echo "tests-result={"status":"failed"}" >> $GITHUB_ENV
+        #   exit 1
+        # fi
 
 
   analyze-test-results:
