refactor: update

diff --git a/.github/workflows/on-pull-request.yml b/.github/workflows/on-pull-request.yml
--- a/.github/workflows/on-pull-request.yml
+++ b/.github/workflows/on-pull-request.yml
@@ -68,15 +68,13 @@ jobs:
 
       - name: Check Jest failures]
         run: |
-          result=needs.unit-test.outputs.tests-result
-          failures=$(echo $result | jq '.testResults[] | select(.status === "failed")' | jq length)
-          if [[ $failures -gt 0 ]]; then
-            echo "Jest test failures found!"
-            echo "tests-failed=true" >> $GITHUB_ENV
+          result=$(npm run test:unit --json 2>/dev/null)
+          if [ $? -eq 0 ]; then
+            echo "tests-result=$result" >> $GITHUB_ENV
           else
-            echo "Jest test passed!"
-            echo "tests-failed=false" >> $GITHUB_ENV
+            echo "tests-result=Error running unit tests" >> $GITHUB_ENV
           fi
+          
         # run: |
         #   failures=$(grep -c "<failure" ./report.xml)
         #   if [[ $failures -gt 0 ]]; then
