refactor: update

diff --git a/.github/workflows/on-pull-request.yml b/.github/workflows/on-pull-request.yml
--- a/.github/workflows/on-pull-request.yml
+++ b/.github/workflows/on-pull-request.yml
@@ -49,13 +49,44 @@ jobs:
       - name: Install dependencies
         run: npm install
 
-      - name: Run unit tests
+      # - name: Run unit tests
+      #   run: |
+      #     if ! npm run test:unit; then
+      #       echo "tests-failed=true" >> $GITHUB_ENV
+      #       exit 0
+      #     else
+      #       echo "tests-failed=false" >> $GITHUB_ENV
+      #     fi
+
+      - name: Run Jest tests
+        run: npm run test:unit -- --testResultsProcessor jest-junit
+
+      - name: Upload test results
+        uses: actions/upload-artifact@v3
+        with:
+          name: test-results
+          path: test-results.xml
+
+  analyze-test-results:
+    runs-on: ubuntu-latest
+
+    needs: unit-tests
+
+    steps:
+      - name: Download test results
+        uses: actions/download-artifact@v2
+        with:
+          name: test-results
+
+      - name: Check Jest failures
         run: |
-          if ! npm run test:unit; then
-            echo "tests-failed=true" >> $GITHUB_ENV
-            exit 0
+          failures=$(grep -c "<failure" test-results.xml)
+          if [[ $failures -gt 0 ]]; then
+            echo "Jest test failures found!"
+            echo "::set-output name=tests-failed::true"
           else
-            echo "tests-failed=false" >> $GITHUB_ENV
+            echo "Jest test passed!"
+            echo "::set-output name=tests-failed::false"
           fi
 
   approve-pr:
@@ -91,7 +122,7 @@ jobs:
 
       - name: Requisitando mudanças ao Pull Request
         run: |
-          gh pr review $PR_NUMBER --request-changes --body "Please make necessary changes."
+          gh pr review $PR_NUMBER --request-changes --body "Necessário corrigir os testes."
 
   lock-pr:
     needs: request-changes-pr
